= advent(6) =
:doctype: manpage

== NAME ==
advent - Colossal Cave Adventure

== SYNOPSIS ==
*advent* [-l logfile] [-o] [-r savefile] [-s]

== DESCRIPTION ==
The original Colossal Cave Adventure from 1976-77 was the origin of all
later text adventures, dungeon-crawl (computer) games, and computer-hosted
roleplaying games.

This is the last version released by Crowther & Woods, its original
authors, in 1995.  It has been known as "adventure 2.5" and "430-point
adventure".  To learn more about the changes since the 350-point
original, type 'news' at the command prompt.

There is an 'adventure' in the BSD games package that is a C port by
Jim Gillogly of the 1976 ancestor of this game.  To avoid a name
collision, this game builds as 'advent', reflecting the fact that the
PDP-10 on which the game originally ran limited filenames to 6 characters.

This version is released as open source with the permission and
encouragement of the original authors.

Unlike the original, this version supports use of your arrow keys to edit
your command line in place.  Basic Emacs keystrokes are supported, and
your up/down arrows access a command history.

Otherwise, the "version" command is about the only way to tell you're not
running Don's original.

To exit the game, type Ctrl-D (EOF).

There have been no gameplay changes.

== OPTIONS ==

-l:: Log commands to specified file.

-s:: Suppress Emacs-like line editing and command history.

-r:: Restore game from specified file

-o:: Old-style.  Restores original interface, no prompt or line editing.

== BUGS ==

The binary save file format is fragile, dependent on your machine word
size and endianness, and unlikely to survive through version bumps. There
is a version check.

== REPORTING BUGS ==
Report bugs to Eric S. Raymond <esr@thyrsus.com>.  The project page is
at http://catb.org/~esr/open-adventure

== SEE ALSO ==
wumpus(6), adventure(6), zork(6), rogue(6), nethack(6).
