extern const long RTXSIZ;
extern const long CLSMAX;
extern const long LOCSIZ;
extern const long LINSIZ;
extern const long TRNSIZ;
extern const long TABSIZ;
extern const long VRBSIZ;
extern long LINUSE;
extern long TRVS;
extern long CLSSES;
extern long TRNVLS;
extern long TABNDX;
extern long HNTMAX;
extern long PTEXT[101];
extern long RTEXT[278];
extern long CTEXT[13];
extern long OBJSND[101];
extern long OBJTXT[101];
extern long STEXT[186];
extern long LTEXT[186];
extern long COND[186];
extern long KEY[186];
extern long LOCSND[186];
extern long LINES[12500];
extern long CVAL[13];
extern long TTEXT[6];
extern long TRNVAL[6];
extern long TRAVEL[886];
extern long KTAB[331];
extern long ATAB[331];
extern long PLAC[101];
extern long FIXD[101];
extern long ACTSPK[36];
extern long HINTS[21][5];
