#include <stdio.h>
#include "newdb.h"

char* long_location_descriptions[] = {
  NULL,
  "You are standing at the end of a road before a small brick building.\nAround you is a forest.  A small stream flows out of the building and\ndown a gully.",
  "You have walked up a hill, still in the forest.  The road slopes back\ndown the other side of the hill.  There is a building in the distance.",
  "You are inside a building, a well house for a large spring.",
  "You are in a valley in the forest beside a stream tumbling along a\nrocky bed.",
  "The road, which approaches from the east, ends here amid the trees.",
  "The forest thins out here to reveal a steep cliff.  There is no way\ndown, but a small ledge can be seen to the west across the chasm.",
  "At your feet all the water of the stream splashes into a 2-inch slit\nin the rock.  Downstream the streambed is bare rock.",
  "You are in a 20-foot depression floored with bare dirt.  Set into the\ndirt is a strong steel grate mounted in concrete.  A dry streambed\nleads into the depression.",
  "You are in a small chamber beneath a 3x3 steel grate to the surface.\nA low crawl over cobbles leads inward to the west.",
  "You are crawling over cobbles in a low passage.  There is a dim light\nat the east end of the passage.",
  "You are in a debris room filled with stuff washed in from the surface.\nA low wide passage with cobbles becomes plugged with mud and debris\nhere, but an awkward canyon leads upward and west.  In the mud someone\nhas scrawled, \"MAGIC WORD XYZZY\".",
  "You are in an awkward sloping east/west canyon.",
  "You are in a splendid chamber thirty feet high.  The walls are frozen\nrivers of orange stone.  An awkward canyon and a good passage exit\nfrom east and west sides of the chamber.",
  "At your feet is a small pit breathing traces of white mist.  An east\npassage ends here except for a small crack leading on.",
  "You are at one end of a vast hall stretching forward out of sight to\nthe west.  There are openings to either side.  Nearby, a wide stone\nstaircase leads downward.  The hall is filled with wisps of white mist\nswaying to and fro almost as if alive.  A cold wind blows up the\nstaircase.  There is a passage at the top of a dome behind you.",
  "The crack is far too small for you to follow.  At its widest it is\nbarely wide enough to admit your foot.",
  "You are on the east bank of a fissure slicing clear across the hall.\nThe mist is quite thick here, and the fissure is too wide to jump.",
  "This is a low room with a crude note on the wall.  The note says,\n\"You won\'t get it up the steps\".",
  "You are in the Hall of the Mountain King, with passages off in all\ndirections.",
  "You are at the bottom of the pit with a broken neck.",
  "You didn\'t make it.",
  "The dome is unclimbable.",
  "You are at the west end of the Twopit Room.  There is a large hole in\nthe wall above the pit at this end of the room.",
  "You are at the bottom of the eastern pit in the Twopit Room.  There is\na small pool of oil in one corner of the pit.",
  "You are at the bottom of the western pit in the Twopit Room.  There is\na large hole in the wall about 25 feet above you.",
  "You clamber up the plant and scurry through the hole at the top.",
  "You are on the west side of the fissure in the Hall of Mists.",
  "You are in a low n/s passage at a hole in the floor.  The hole goes\ndown to an e/w passage.",
  "You are in the south side chamber.",
  "You are in the west side chamber of the Hall of the Mountain King.\nA passage continues west and up here.",
  "",
  "You can\'t get by the snake.",
  "You are in a large room, with a passage to the south, a passage to the\nwest, and a wall of broken rock to the east.  There is a large \"Y2\" on\na rock in the room\'s center.",
  "You are in a jumble of rock, with cracks everywhere.",
  "You\'re at a low window overlooking a huge pit, which extends up out of\nsight.  A floor is indistinctly visible over 50 feet below.  Traces of\nwhite mist cover the floor of the pit, becoming thicker to the right.\nMarks in the dust around the window would seem to indicate that\nsomeone has been here recently.  Directly across the pit from you and\n25 feet away there is a similar window looking into a lighted room.  A\nshadowy figure can be seen there peering back at you.",
  "You are in a dirty broken passage.  To the east is a crawl.  To the\nwest is a large passage.  Above you is a hole to another passage.",
  "You are on the brink of a small clean climbable pit.  A crawl leads\nwest.",
  "You are in the bottom of a small pit with a little stream, which\nenters and exits through tiny slits.",
  "You are in a large room full of dusty rocks.  There is a big hole in\nthe floor.  There are cracks everywhere, and a passage leading east.",
  "You have crawled through a very low wide passage parallel to and north\nof the Hall of Mists.",
  "You are at the west end of the Hall of Mists.  A low wide crawl\ncontinues west and another goes north.  To the south is a little\npassage 6 feet off the floor.",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a maze of twisty little passages, all alike.",
  "Dead end",
  "Dead end",
  "Dead end",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a maze of twisty little passages, all alike.",
  "Dead end",
  "You are in a maze of twisty little passages, all alike.",
  "Dead end",
  "You are on the brink of a thirty foot pit with a massive orange column\ndown one wall.  You could climb down here but you could not get back\nup.  The maze continues at this level.",
  "Dead end",
  "You have crawled through a very low wide passage parallel to and north\nof the Hall of Mists.",
  "You are at the east end of a very long hall apparently without side\nchambers.  To the east a low wide crawl slants up.  To the north a\nround two foot hole slants down.",
  "You are at the west end of a very long featureless hall.  The hall\njoins up with a narrow north/south passage.",
  "You are at a crossover of a high n/s passage and a low e/w one.",
  "Dead end",
  "You are at a complex junction.  A low hands and knees passage from the\nnorth joins a higher crawl from the east to make a walking passage\ngoing west.  There is also a large room above.  The air is damp here.",
  "You are in Bedquilt, a long east/west passage with holes everywhere.\nTo explore at random select north, south, up, or down.",
  "You are in a room whose walls resemble swiss cheese.  Obvious passages\ngo west, east, ne, and nw.  Part of the room is occupied by a large\nbedrock block.",
  "You are at the east end of the Twopit Room.  The floor here is\nlittered with thin rock slabs, which make it easy to descend the pits.\nThere is a path here bypassing the pits to connect passages from east\nand west.  There are holes all over, but the only big one is on the\nwall directly over the west pit where you can\'t get to it.",
  "You are in a large low circular chamber whose floor is an immense slab\nfallen from the ceiling (Slab Room).  East and west there once were\nlarge passages, but they are now filled with boulders.  Low small\npassages go north and south, and the south one quickly bends west\naround the boulders.",
  "You are in a secret n/s canyon above a large room.",
  "You are in a secret n/s canyon above a sizable passage.",
  "You are in a secret canyon at a junction of three canyons, bearing\nnorth, south, and se.  The north one is as tall as the other two\ncombined.",
  "You are in a large low room.  Crawls lead north, se, and sw.",
  "Dead end crawl.",
  "You are in a secret canyon which here runs e/w.  It crosses over a\nvery tight canyon 15 feet below.  If you go down you may not be able\nto get back up.",
  "You are at a wide place in a very tight n/s canyon.",
  "The canyon here becomes too tight to go further south.",
  "You are in a tall e/w canyon.  A low tight crawl goes 3 feet north and\nseems to open up.",
  "The canyon runs into a mass of boulders -- dead end.",
  "The stream flows out through a pair of 1 foot diameter sewer pipes.\nIt would be advisable to use the exit.",
  "You are in a maze of twisty little passages, all alike.",
  "Dead end",
  "Dead end",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a maze of twisty little passages, all alike.",
  "Dead end",
  "Dead end",
  "You are in a maze of twisty little passages, all alike.",
  "You are in a long, narrow corridor stretching out of sight to the\nwest.  At the eastern end is a hole through which you can see a\nprofusion of leaves.",
  "There is nothing here to climb.  Use \"up\" or \"out\" to leave the pit.",
  "You have climbed up the plant and out of the pit.",
  "You are at the top of a steep incline above a large room.  You could\nclimb down here, but you would not be able to climb up.  There is a\npassage leading back to the north.",
  "You are in the Giant Room.  The ceiling here is too high up for your\nlamp to show it.  Cavernous passages lead east, north, and south.  On\nthe west wall is scrawled the inscription, \"FEE FIE FOE FOO\" [sic].",
  "The passage here is blocked by a recent cave-in.",
  "You are at one end of an immense north/south passage.",
  "You are in a magnificent cavern with a rushing stream, which cascades\nover a sparkling waterfall into a roaring whirlpool which disappears\nthrough a hole in the floor.  Passages exit to the south and west.",
  "You are in the Soft Room.  The walls are covered with heavy curtains,\nthe floor with a thick pile carpet.  Moss covers the ceiling.",
  "This is the Oriental Room.  Ancient oriental cave drawings cover the\nwalls.  A gently sloping passage leads upward to the north, another\npassage leads se, and a hands and knees crawl leads west.",
  "You are following a wide path around the outer edge of a large cavern.\nFar below, through a heavy white mist, strange splashing noises can be\nheard.  The mist rises up through a fissure in the ceiling.  The path\nexits to the south and west.",
  "You are in an alcove.  A small nw path seems to widen after a short\ndistance.  An extremely tight tunnel leads east.  It looks like a very\ntight squeeze.  An eerie light can be seen at the other end.",
  "You\'re in a small chamber lit by an eerie green light.  An extremely\nnarrow tunnel exits to the west.  A dark corridor leads ne.",
  "You\'re in the dark-room.  A corridor leading south is the only exit.",
  "You are in an arched hall.  A coral passage once continued up and east\nfrom here, but is now blocked by debris.  The air smells of sea water.",
  "You\'re in a large room carved out of sedimentary rock.  The floor and\nwalls are littered with bits of shells imbedded in the stone.  A\nshallow passage proceeds downward, and a somewhat steeper one leads\nup.  A low hands and knees passage enters from the south.",
  "You are in a long sloping corridor with ragged sharp walls.",
  "You are in a cul-de-sac about eight feet across.",
  "You are in an anteroom leading to a large passage to the east.  Small\npassages go west and up.  The remnants of recent digging are evident.\nA sign in midair here says \"Cave under construction beyond this point.\nProceed at own risk.  [Witt Construction Company]\"",
  "You are in a maze of twisty little passages, all different.",
  "You are at Witt\'s End.  Passages lead off in *ALL* directions.",
  "You are in a north/south canyon about 25 feet across.  The floor is\ncovered by white mist seeping in from the north.  The walls extend\nupward for well over 100 feet.  Suspended from some unseen point far\nabove you, an enormous two-sided mirror is hanging parallel to and\nmidway between the canyon walls.  (The mirror is obviously provided\nfor the use of the dwarves who, as you know, are extremely vain.)  A\nsmall window can be seen in either wall, some fifty feet up.",
  "You\'re at a low window overlooking a huge pit, which extends up out of\nsight.  A floor is indistinctly visible over 50 feet below.  Traces of\nwhite mist cover the floor of the pit, becoming thicker to the left.\nMarks in the dust around the window would seem to indicate that\nsomeone has been here recently.  Directly across the pit from you and\n25 feet away there is a similar window looking into a lighted room.  A\nshadowy figure can be seen there peering back at you.",
  "A large stalactite extends from the roof and almost reaches the floor\nbelow.  You could climb down it, and jump from it to the floor, but\nhaving done so you would be unable to reach it to climb back up.",
  "You are in a little maze of twisting passages, all different.",
  "You are at the edge of a large underground reservoir.  An opaque cloud\nof white mist fills the room and rises rapidly upward.  The lake is\nfed by a stream, which tumbles out of a hole in the wall about 10 feet\noverhead and splashes noisily into the water somewhere within the\nmist.  There is a passage going back toward the south.",
  "Dead end",
  "You are at the northeast end of an immense room, even larger than the\nGiant Room.  It appears to be a repository for the \"Adventure\"\nprogram.  Massive torches far overhead bathe the room with smoky\nyellow light.  Scattered about you can be seen a pile of bottles (all\nof them empty), a nursery of young beanstalks murmuring quietly, a bed\nof oysters, a bundle of black rods with rusty stars on their ends, and\na collection of brass lanterns.  Off to one side a great many dwarves\nare sleeping on the floor, snoring loudly.  A notice nearby reads: \"Do\nnot disturb the dwarves!\"  An immense mirror is hanging against one\nwall, and stretches to the other end of the room, where various other\nsundry objects can be glimpsed dimly in the distance.",
  "You are at the southwest end of the repository.  To one side is a pit\nfull of fierce green snakes.  On the other side is a row of small\nwicker cages, each of which contains a little sulking bird.  In one\ncorner is a bundle of black rods with rusty marks on their ends.  A\nlarge number of velvet pillows are scattered about on the floor.  A\nvast mirror stretches off to the northeast.  At your feet is a large\nsteel grate, next to which is a sign that reads, \"Treasure Vault.\nKeys in main office.\"",
  "You are on one side of a large, deep chasm.  A heavy white mist rising\nup from below obscures all view of the far side.  A sw path leads away\nfrom the chasm into a winding corridor.",
  "You are in a long winding corridor sloping out of sight in both\ndirections.",
  "You are in a secret canyon which exits to the north and east.",
  "You are in a secret canyon which exits to the north and east.",
  "You are in a secret canyon which exits to the north and east.",
  "You are on the far side of the chasm.  A ne path leads away from the\nchasm on this side.",
  "You\'re in a long east/west corridor.  A faint rumbling noise can be\nheard in the distance.",
  "The path forks here.  The left fork leads northeast.  A dull rumbling\nseems to get louder in that direction.  The right fork leads southeast\ndown a gentle slope.  The main corridor enters from the west.",
  "The walls are quite warm here.  From the north can be heard a steady\nroar, so loud that the entire cave seems to be trembling.  Another\npassage leads south, and a low crawl goes east.",
  "You are on the edge of a breath-taking view.  Far below you is an\nactive volcano, from which great gouts of molten lava come surging\nout, cascading back down into the depths.  The glowing rock fills the\nfarthest reaches of the cavern with a blood-red glare, giving every-\nthing an eerie, macabre appearance.  The air is filled with flickering\nsparks of ash and a heavy smell of brimstone.  The walls are hot to\nthe touch, and the thundering of the volcano drowns out all other\nsounds.  Embedded in the jagged roof far overhead are myriad twisted\nformations composed of pure white alabaster, which scatter the murky\nlight into sinister apparitions upon the walls.  To one side is a deep\ngorge, filled with a bizarre chaos of tortured rock which seems to\nhave been crafted by the devil himself.  An immense river of fire\ncrashes out from the depths of the volcano, burns its way through the\ngorge, and plummets into a bottomless pit far off to your left.  To\nthe right, an immense geyser of blistering steam erupts continuously\nfrom a barren island in the center of a sulfurous lake, which bubbles\nominously.  The far right wall is aflame with an incandescence of its\nown, which lends an additional infernal splendor to the already\nhellish scene.  A dark, foreboding passage exits to the south.",
  "You are in a small chamber filled with large boulders.  The walls are\nvery warm, causing the air in the room to be almost stifling from the\nheat.  The only exit is a crawl heading west, through which is coming\na low rumbling.",
  "You are walking along a gently sloping north/south passage lined with\noddly shaped limestone formations.",
  "You are standing at the entrance to a large, barren room.  A notice\nabove the entrance reads:  \"Caution!  Bear in room!\"",
  "You are inside a barren room.  The center of the room is completely\nempty except for some dust.  Marks in the dust lead away toward the\nfar end of the room.  The only exit is the way you came in.",
  "You are in a maze of twisting little passages, all different.",
  "You are in a little maze of twisty passages, all different.",
  "You are in a twisting maze of little passages, all different.",
  "You are in a twisting little maze of passages, all different.",
  "You are in a twisty little maze of passages, all different.",
  "You are in a twisty maze of little passages, all different.",
  "You are in a little twisty maze of passages, all different.",
  "You are in a maze of little twisting passages, all different.",
  "You are in a maze of little twisty passages, all different.",
  "Dead end",
  "You are in a long, rough-hewn, north/south corridor.",
  "There is no way to go that direction.",
  "You are in a large chamber with passages to the west and north.",
  "You are in the ogre\'s storeroom.  The only exit is to the south.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are wandering aimlessly through the forest.",
  "You are on a small ledge on one face of a sheer cliff.  There are no\npaths away from the ledge.  Across the chasm is a small clearing\nsurrounded by forest.",
  "You are walking across the bottom of the reservoir.  Walls of water\nrear up on either side.  The roar of the water cascading past is\nnearly deafening, and the mist is so thick you can barely see.",
  "You are at the northern edge of the reservoir.  A northwest passage\nleads sharply up from here.",
  "You are scrambling along a treacherously steep, rocky passage.",
  "You are on a very steep incline, which widens at it goes upward.",
  "You are at the base of a nearly vertical cliff.  There are some\nslim footholds which would enable you to climb up, but it looks\nextremely dangerous.  Here at the base of the cliff lie the remains\nof several earlier adventurers who apparently failed to make it.",
  "You are climbing along a nearly vertical cliff.",
  "Just as you reach the top, your foot slips on a loose rock and you\ntumble several hundred feet to join the other unlucky adventurers.",
  "Just as you reach the top, your foot slips on a loose rock and you\nmake one last desperate grab.  Your luck holds, as does your grip.\nWith an enormous heave, you lift yourself to the ledge above.",
  "You are on a small ledge at the top of a nearly vertical cliff.\nThere is a low crawl leading off to the northeast.",
  "You have reached a dead end.",
  "There is now one more gruesome aspect to the spectacular vista.",
  ">>Foof!<<",
  ">>Foof!<<",
  ">>Foof!<<",
  ">>Foof!<<",
  ">>Foof!<<",
  ">>Foof!<<",
  NULL,
};

char* short_location_descriptions[] = {
  NULL,
  "You\'re in front of building.",
  "You\'re at hill in road.",
  "You\'re inside building.",
  "You\'re in valley.",
  "You\'re at end of road.",
  "You\'re at cliff.",
  "You\'re at slit in streambed.",
  "You\'re outside grate.",
  "You\'re below the grate.",
  "You\'re in cobble crawl.",
  "You\'re in debris room.",
  NULL,
  "You\'re in bird chamber.",
  "You\'re at top of small pit.",
  "You\'re in Hall of Mists.",
  NULL,
  "You\'re on east bank of fissure.",
  "You\'re in nugget-of-gold room.",
  "You\'re in Hall of Mt King.",
  NULL,
  NULL,
  NULL,
  "You\'re at west end of Twopit Room.",
  "You\'re in east pit.",
  "You\'re in west pit.",
  NULL,
  "You\'re on west bank of fissure.",
  "You\'re in n/s passage above e/w passage.",
  NULL,
  "You\'re in the west side chamber.",
  NULL,
  NULL,
  "You\'re at \"Y2\".",
  NULL,
  "You\'re at window on pit.",
  "You\'re in dirty passage.",
  "You\'re at brink of small pit.",
  "You\'re at bottom of pit with stream.",
  "You\'re in dusty rock room.",
  NULL,
  "You\'re at west end of Hall of Mists.",
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  "You\'re at brink of pit.",
  NULL,
  NULL,
  "You\'re at east end of long hall.",
  "You\'re at west end of long hall.",
  NULL,
  NULL,
  "You\'re at complex junction.",
  "You\'re in Bedquilt.",
  "You\'re in Swiss Cheese Room.",
  "You\'re at east end of Twopit Room.",
  "You\'re in Slab Room.",
  NULL,
  NULL,
  "You\'re at junction of three secret canyons.",
  "You\'re in large low room.",
  NULL,
  "You\'re in secret e/w canyon above tight canyon.",
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  "You\'re in narrow corridor.",
  NULL,
  NULL,
  "You\'re at steep incline above large room.",
  "You\'re in Giant Room.",
  NULL,
  NULL,
  "You\'re in cavern with waterfall.",
  "You\'re in Soft Room.",
  "You\'re in Oriental Room.",
  "You\'re in misty cavern.",
  "You\'re in alcove.",
  "You\'re in Plover Room.",
  "You\'re in dark-room.",
  "You\'re in arched hall.",
  "You\'re in Shell Room.",
  NULL,
  NULL,
  "You\'re in anteroom.",
  NULL,
  "You\'re at Witt\'s End.",
  "You\'re in Mirror Canyon.",
  "You\'re at window on pit.",
  "You\'re at top of stalactite.",
  NULL,
  "You\'re at reservoir.",
  NULL,
  "You\'re at ne end.",
  "You\'re at sw end.",
  "You\'re on sw side of chasm.",
  "You\'re in sloping corridor.",
  NULL,
  NULL,
  NULL,
  "You\'re on ne side of chasm.",
  "You\'re in corridor.",
  "You\'re at fork in path.",
  "You\'re at junction with warm walls.",
  "You\'re at breath-taking view.",
  "You\'re in Chamber of Boulders.",
  "You\'re in limestone passage.",
  "You\'re in front of Barren Room.",
  "You\'re in Barren Room.",
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  "You\'re on ledge.",
  "You\'re at bottom of reservoir.",
  "You\'re north of reservoir.",
  NULL,
  NULL,
  "You\'re at base of cliff.",
  NULL,
  NULL,
  NULL,
  "You\'re at top of cliff.",
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
};

object_description_s object_descriptions[] = {
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = "Set of keys",
    .longs = (char* []) {
      "There are some keys on the ground here.",
    },
  },
  {
    .inventory = "Brass lantern",
    .longs = (char* []) {
      "There is a shiny brass lamp nearby.",
      "There is a lamp shining nearby.",
    },
  },
  {
    .inventory = "*grate",
    .longs = (char* []) {
      "The grate is locked.",
      "The grate is open.",
    },
  },
  {
    .inventory = "Wicker cage",
    .longs = (char* []) {
      "There is a small wicker cage discarded nearby.",
    },
  },
  {
    .inventory = "Black rod",
    .longs = (char* []) {
      "A three foot black rod with a rusty star on an end lies nearby.",
    },
  },
  {
    .inventory = "Black rod",
    .longs = (char* []) {
      "A three foot black rod with a rusty mark on an end lies nearby.",
    },
  },
  {
    .inventory = "*steps",
    .longs = (char* []) {
      "Rough stone steps lead down the pit.",
      "Rough stone steps lead up the dome.",
    },
  },
  {
    .inventory = "Little bird in cage",
    .longs = (char* []) {
      "A cheerful little bird is sitting here singing.",
      "There is a little bird in the cage.",
      "A cheerful little bird is sitting here singing.",
      "The bird\'s singing is quite melodious.",
      "The bird does not seem inclined to sing while in the cage.",
      "It almost seems as though the bird is trying to tell you something.",
      "To your surprise, you can understand the bird\'s chirping; it is\nsinging about the joys of its forest home.",
      "The bird does not seem inclined to sing while in the cage.",
      "The bird is singing to you in gratitude for your having returned it to\nits home.  In return, it informs you of a magic word which it thinks\nyou may find useful somewhere near the Hall of Mists.  The magic word\nchanges frequently, but for now the bird believes it is \"%s\".  You\nthank the bird for this information, and it flies off into the forest.",
    },
  },
  {
    .inventory = "*rusty door",
    .longs = (char* []) {
      "The way north is barred by a massive, rusty, iron door.",
      "The way north leads through a massive, rusty, iron door.",
    },
  },
  {
    .inventory = "Velvet pillow",
    .longs = (char* []) {
      "A small velvet pillow lies on the floor.",
    },
  },
  {
    .inventory = "*snake",
    .longs = (char* []) {
      "A huge green fierce snake bars the way!",
      "", // (chased away)
      "The snake is hissing venomously.",
    },
  },
  {
    .inventory = "*fissure",
    .longs = (char* []) {
      "",
      "A crystal bridge now spans the fissure.",
      "The crystal bridge has vanished!",
    },
  },
  {
    .inventory = "*stone tablet",
    .longs = (char* []) {
      "A massive stone tablet imbedded in the wall reads:\n\"Congratulations on bringing light into the dark-room!\"",
      "\"Congratulations on bringing light into the dark-room!\"",
    },
  },
  {
    .inventory = "Giant clam  >GRUNT!<",
    .longs = (char* []) {
      "There is an enormous clam here with its shell tightly closed.",
      "The clam is as tight-mouthed as a, er, clam.",
    },
  },
  {
    .inventory = "Giant oyster  >GROAN!<",
    .longs = (char* []) {
      "There is an enormous oyster here with its shell tightly closed.",
      "Interesting.  There seems to be something written on the underside of\nthe oyster.",
      "Even though it\'s an oyster, the critter\'s as tight-mouthed as a clam.",
      "It says the same thing it did before.  Hm, maybe it\'s a pun?",
    },
  },
  {
    .inventory = "\"Spelunker Today\"",
    .longs = (char* []) {
      "There are a few recent issues of \"Spelunker Today\" magazine here.",
      "I\'m afraid the magazine is written in dwarvish.  But pencilled on one\ncover you see, \"Please leave the magazines at the construction site.\"",
    },
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = "Tasty food",
    .longs = (char* []) {
      "There is food here.",
    },
  },
  {
    .inventory = "Small bottle",
    .longs = (char* []) {
      "There is a bottle of water here.",
      "There is an empty bottle here.",
      "There is a bottle of oil here.",
    },
  },
  {
    .inventory = "Water in the bottle",
    .longs = (char* []) {
    },
  },
  {
    .inventory = "Oil in the bottle",
    .longs = (char* []) {
    },
  },
  {
    .inventory = "*mirror",
    .longs = (char* []) {
      "",
    },
  },
  {
    .inventory = "*plant",
    .longs = (char* []) {
      "There is a tiny little plant in the pit, murmuring \"water, water, ...\"",
      "There is a 12-foot-tall beanstalk stretching up out of the pit,\nbellowing \"WATER!! WATER!!\"",
      "There is a gigantic beanstalk stretching all the way up to the hole.",
      "The plant spurts into furious growth for a few seconds.",
      "The plant grows explosively, almost filling the bottom of the pit.",
      "You\'ve over-watered the plant!  It\'s shriveling up!  And now . . .",
      "The plant continues to ask plaintively for water.",
      "The plant continues to demand water.",
      "The plant now maintains a contented silence.",
    },
  },
  {
    .inventory = "*phony plant (seen in Twopit Room only when tall enough)",
    .longs = (char* []) {
      "",
      "The top of a 12-foot-tall beanstalk is poking out of the west pit.",
      "There is a huge beanstalk growing out of the west pit up to the hole.",
    },
  },
  {
    .inventory = "*stalactite",
    .longs = (char* []) {
      "",
    },
  },
  {
    .inventory = "*shadowy figure and/or window",
    .longs = (char* []) {
      "The shadowy figure seems to be trying to attract your attention.",
    },
  },
  {
    .inventory = "Dwarf\'s axe",
    .longs = (char* []) {
      "There is a little axe here.",
      "There is a little axe lying beside the bear.",
    },
  },
  {
    .inventory = "*cave drawings",
    .longs = (char* []) {
      "",
    },
  },
  {
    .inventory = "*pirate/genie",
    .longs = (char* []) {
      "  (never present)",
    },
  },
  {
    .inventory = "*dragon",
    .longs = (char* []) {
      "A huge green fierce dragon bars the way!",
      "The blood-specked body of a huge green dead dragon lies to one side.",
      "The body of a huge green dead dragon is lying off to one side.",
      "Congratulations!  You have just vanquished a dragon with your bare\nhands!  (Unbelievable, isn\'t it?)",
      "The dragon\'s ominous hissing does not bode well for you.",
      "The dragon is, not surprisingly, silent.",
      "The dragon is, not surprisingly, silent.",
    },
  },
  {
    .inventory = "*chasm",
    .longs = (char* []) {
      "A rickety wooden bridge extends across the chasm, vanishing into the\nmist.  A notice posted on the bridge reads, \"Stop! Pay troll!\"",
      "The wreckage of a bridge (and a dead bear) can be seen at the bottom\nof the chasm.",
    },
  },
  {
    .inventory = "*troll",
    .longs = (char* []) {
      "A burly troll stands by the bridge and insists you throw him a\ntreasure before you may cross.",
      "The troll steps out from beneath the bridge and blocks your way.",
      "", // (chased away)
      "The troll sounds quite adamant in his demand for a treasure.",
    },
  },
  {
    .inventory = "*phony troll",
    .longs = (char* []) {
      "The troll is nowhere to be seen.",
    },
  },
  {
    .inventory = "", // (bear uses rtext 141)
    .longs = (char* []) {
      "There is a ferocious cave bear eying you from the far end of the room!",
      "There is a gentle cave bear sitting placidly in one corner.",
      "There is a contented-looking bear wandering about nearby.",
      "", // (dead)
    },
  },
  {
    .inventory = "*message in second maze",
    .longs = (char* []) {
      "There is a message scrawled in the dust in a flowery script, reading:\n\"This is not the maze where the pirate leaves his treasure chest.\"",
      "\"This is not the maze where the pirate leaves his treasure chest.\"",
    },
  },
  {
    .inventory = "*volcano and/or geyser",
    .longs = (char* []) {
      "",
    },
  },
  {
    .inventory = "*vending machine",
    .longs = (char* []) {
      "There is a massive and somewhat battered vending machine here.  The\ninstructions on it read: \"Drop coins here to receive fresh batteries.\"",
      "\"Drop coins here to receive fresh batteries.\"",
      "As you strike the vending machine, it pivots backward along with a\nsection of wall, revealing a dark passage leading south.",
      "There is a massive vending machine here, swung back to reveal a\nsouthward passage.",
      "\"Drop coins here to receive fresh batteries.\"",
      "The vending machine swings back to block the passage.",
    },
  },
  {
    .inventory = "Batteries",
    .longs = (char* []) {
      "There are fresh batteries here.",
      "Some worn-out batteries have been discarded nearby.",
    },
  },
  {
    .inventory = "*carpet and/or moss and/or curtains",
    .longs = (char* []) {
      "",
    },
  },
  {
    .inventory = "*ogre",
    .longs = (char* []) {
      "A formidable ogre bars the northern exit.",
      "The ogre is apparently the strong, silent type.",
    },
  },
  {
    .inventory = "*urn",
    .longs = (char* []) {
      "A small urn is embedded in the rock.",
      "A small urn full of oil is embedded in the rock.",
      "A small oil flame extrudes from an urn embedded in the rock.",
    },
  },
  {
    .inventory = "*cavity",
    .longs = (char* []) {
      "", // (something in it)
      "There is a small urn-shaped cavity in the rock.",
    },
  },
  {
    .inventory = "*blood",
    .longs = (char* []) {
      "", // (described with dragon)
    },
  },
  {
    .inventory = "*reservoir",
    .longs = (char* []) {
      "",
      "The waters have parted to form a narrow path across the reservoir.",
      "The waters crash together again.",
    },
  },
  {
    .inventory = "Leporine appendage",
    .longs = (char* []) {
      "Your keen eye spots a severed leporine appendage lying on the ground.",
    },
  },
  {
    .inventory = "*mud",
    .longs = (char* []) {
      "",
      "\"MAGIC WORD XYZZY\"",
    },
  },
  {
    .inventory = "*note",
    .longs = (char* []) {
      "",
      "\"You won\'t get it up the steps\"",
    },
  },
  {
    .inventory = "*sign",
    .longs = (char* []) {
      "",
      "Cave under construction beyond this point.\n           Proceed at own risk.\n       [Witt Construction Company]",
      "\"Treasure Vault.  Keys in main office.\"",
    },
  },
  {
    .inventory = "Large gold nugget",
    .longs = (char* []) {
      "There is a large sparkling nugget of gold here!",
    },
  },
  {
    .inventory = "Several diamonds",
    .longs = (char* []) {
      "There are diamonds here!",
    },
  },
  {
    .inventory = "Bars of silver",
    .longs = (char* []) {
      "There are bars of silver here!",
    },
  },
  {
    .inventory = "Precious jewelry",
    .longs = (char* []) {
      "There is precious jewelry here!",
    },
  },
  {
    .inventory = "Rare coins",
    .longs = (char* []) {
      "There are many coins here!",
    },
  },
  {
    .inventory = "Treasure chest",
    .longs = (char* []) {
      "The pirate\'s treasure chest is here!",
    },
  },
  {
    .inventory = "Golden eggs",
    .longs = (char* []) {
      "There is a large nest here, full of golden eggs!",
      "The nest of golden eggs has vanished!",
      "Done!",
    },
  },
  {
    .inventory = "Jeweled trident",
    .longs = (char* []) {
      "There is a jewel-encrusted trident here!",
    },
  },
  {
    .inventory = "Ming vase",
    .longs = (char* []) {
      "There is a delicate, precious, ming vase here!",
      "The vase is now resting, delicately, on a velvet pillow.",
      "The floor is littered with worthless shards of pottery.",
      "The ming vase drops with a delicate crash.",
    },
  },
  {
    .inventory = "Egg-sized emerald",
    .longs = (char* []) {
      "There is an emerald here the size of a plover\'s egg!",
      "There is an emerald resting in a small cavity in the rock!",
    },
  },
  {
    .inventory = "Platinum pyramid",
    .longs = (char* []) {
      "There is a platinum pyramid here, 8 inches on a side!",
    },
  },
  {
    .inventory = "Glistening pearl",
    .longs = (char* []) {
      "Off to one side lies a glistening pearl!",
    },
  },
  {
    .inventory = "Persian rug",
    .longs = (char* []) {
      "There is a persian rug spread out on the floor!",
      "The dragon is sprawled out on a persian rug!!",
      "There is a persian rug here, hovering in mid-air!",
    },
  },
  {
    .inventory = "Rare spices",
    .longs = (char* []) {
      "There are rare spices here!",
    },
  },
  {
    .inventory = "Golden chain",
    .longs = (char* []) {
      "There is a golden chain lying in a heap on the floor!",
      "The bear is locked to the wall with a golden chain!",
      "There is a golden chain locked to the wall!",
    },
  },
  {
    .inventory = "Giant ruby",
    .longs = (char* []) {
      "There is an enormous ruby here!",
      "There is a ruby resting in a small cavity in the rock!",
    },
  },
  {
    .inventory = "Jade necklace",
    .longs = (char* []) {
      "A precious jade necklace has been dropped here!",
    },
  },
  {
    .inventory = "Amber gemstone",
    .longs = (char* []) {
      "There is a rare amber gemstone here!",
      "There is an amber gemstone resting in a small cavity in the rock!",
    },
  },
  {
    .inventory = "Star sapphire",
    .longs = (char* []) {
      "A brilliant blue star sapphire is here!",
      "There is a star sapphire resting in a small cavity in the rock!",
    },
  },
  {
    .inventory = "Ebony statuette",
    .longs = (char* []) {
      "There is a richly-carved ebony statuette here!",
    },
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
  {
    .inventory = NULL,
    .longs = NULL,
  },
};

char* arbitrary_messages[] = {
  NULL,
  "Somewhere nearby is Colossal Cave, where others have found fortunes in\ntreasure and gold, though it is rumored that some who enter are never\nseen again.  Magic is said to work in the cave.  I will be your eyes\nand hands.  Direct me with commands of 1 or 2 words.  I should warn\nyou that I look at only the first five letters of each word, so you\'ll\nhave to enter \"northeast\" as \"ne\" to distinguish it from \"north\".\nYou can type \"help\" for some general hints.  For information on how\nto end your adventure, scoring, etc., type \"info\".\n			      - - -\nThis program was originally developed by Willie Crowther.  Most of the\nfeatures of the current program were added by Don Woods.  Contact Don\nif you have any questions, comments, etc.",
  "A little dwarf with a big knife blocks your way.",
  "A little dwarf just walked around a corner, saw you, threw a little\naxe at you which missed, cursed, and ran away.",
  "There are %d threatening little dwarves in the room with you.",
  "There is a threatening little dwarf in the room with you!",
  "One sharp nasty knife is thrown at you!",
  "A hollow voice says \"PLUGH\".",
  "It gets you!",
  "It misses!",
  "I am unsure how you are facing.  Use compass points or nearby objects.",
  "I don\'t know in from out here.  Use compass points or name something\nin the general direction you want to go.",
  "I don\'t know how to apply that word here.",
  "You\'re quite welcome.",
  "I\'m game.  Would you care to explain how?",
  "Sorry, but I am not allowed to give more detail.  I will repeat the\nlong description of your location.",
  "It is now pitch dark.  If you proceed you will likely fall into a pit.",
  "If you prefer, simply type w rather than west.",
  "Are you trying to catch the bird?",
  "Something about you seems to be frightening the bird.  Perhaps you\nmight figure out what it is.",
  "Are you trying to somehow deal with the snake?",
  "You can\'t kill the snake, or drive it away, or avoid it, or anything\nlike that.  There is a way to get by, but you don\'t have the necessary\nresources right now.",
  "Do you really want to quit now?",
  "You fell into a pit and broke every bone in your body!",
  "You are already carrying it!",
  "You can\'t be serious!",
  "The bird seemed unafraid at first, but as you approach it becomes\ndisturbed and you cannot catch it.",
  "You can catch the bird, but you cannot carry it.",
  "There is nothing here with a lock!",
  "You aren\'t carrying it!",
  "The little bird attacks the green snake, and in an astounding flurry\ndrives the snake away.",
  "You have no keys!",
  "It has no lock.",
  "I don\'t know how to lock or unlock such a thing.",
  "It was already locked.",
  "The grate is now locked.",
  "The grate is now unlocked.",
  "It was already unlocked.",
  "The urn is empty and will not light.",
  "Your lamp is now on.",
  "Your lamp is now off.",
  "There is no way to get past the bear to unlock the chain, which is\nprobably just as well.",
  "Nothing happens.",
  "Where?",
  "There is nothing here to attack.",
  "The little bird is now dead.  Its body disappears.",
  "Attacking the snake both doesn\'t work and is very dangerous.",
  "You killed a little dwarf.",
  "You attack a little dwarf, but he dodges out of the way.",
  "With what?  Your bare hands?",
  "Good try, but that is an old worn-out magic word.",
  "I know of places, actions, and things.  Most of my vocabulary\ndescribes places and is used to move you there.  To move, try words\nlike forest, building, downstream, enter, east, west, north, south,\nup, or down.  I know about a few special objects, like a black rod\nhidden in the cave.  These objects can be manipulated using some of\nthe action words that I know.  Usually you will need to give both the\nobject and action words (in either order), but sometimes I can infer\nthe object from the verb alone.  Some objects also imply verbs; in\nparticular, \"inventory\" implies \"take inventory\", which causes me to\ngive you a list of what you\'re carrying.  Some objects have unexpected\neffects; the effects are not always desirable!  Usually people having\ntrouble moving just need to try a few more words.  Usually people\ntrying unsuccessfully to manipulate an object are attempting something\nbeyond their (or my!) capabilities and should try a completely\ndifferent tack.  One point often confusing to beginners is that, when\nthere are several ways to go in a certain direction (e.g., if there\nare several holes in a wall), choosing that direction in effect\nchooses one of the ways at random; often, though, by specifying the\nplace you want to reach you can guarantee choosing the right path.\nAlso, to speed the game you can sometimes move long distances with a\nsingle word.  For example, \"building\" usually gets you to the building\nfrom anywhere above ground except when lost in the forest.  Also, note\nthat cave passages and forest paths turn a lot, so leaving one place\nheading north doesn\'t guarantee entering the next from the south.\nHowever (another important point), except when you\'ve used a \"long\ndistance\" word such as \"building\", there is always a way to go back\nwhere you just came from unless I warn you to the contrary, even\nthough the direction that takes you back might not be the reverse of\nwhat got you here.  Good luck, and have fun!",
  "There is no way to go that direction.",
  "Please stick to 1- and 2-word commands.",
  "OK",
  "You can\'t unlock the keys.",
  "You have crawled around in some little holes and wound up back in the\nmain passage.",
  "I don\'t know where the cave is, but hereabouts no stream can run on\nthe surface for long.  I would try the stream.",
  "I need more detailed instructions to do that.",
  "I can only tell you what you see as you move about and manipulate\nthings.  I cannot tell you where remote things are.",
  "The ogre snarls and shoves you back.",
  "Huh?",
  "Are you trying to get into the cave?",
  "The grate is very solid and has a hardened steel lock.  You cannot\nenter without a key, and there are no keys nearby.  I would recommend\nlooking elsewhere for the keys.",
  "The trees of the forest are large hardwood oak and maple, with an\noccasional grove of pine or spruce.  There is quite a bit of under-\ngrowth, largely birch and ash saplings plus nondescript bushes of\nvarious sorts.  This time of year visibility is quite restricted by\nall the leaves, but travel is quite easy if you detour around the\nspruce and berry bushes.",
  "Welcome to Adventure!!  Would you like instructions?",
  "Digging without a shovel is quite impractical.  Even with a shovel\nprogress is unlikely.",
  "Blasting requires dynamite.",
  "I\'m as confused as you are.",
  "Mist is a white vapor, usually water, seen from time to time in\ncaverns.  It can be found anywhere but is frequently a sign of a deep\npit leading down to water.",
  "Your feet are now wet.",
  "I think I just lost my appetite.",
  "Thank you, it was delicious!",
  "You have taken a drink from the stream.  The water tastes strongly of\nminerals, but is not unpleasant.  It is extremely cold.",
  "The bottle of water is now empty.",
  "Rubbing the electric lamp is not particularly rewarding.  Anyway,\nnothing exciting happens.",
  "Peculiar.  Nothing unexpected happens.",
  "Your bottle is empty and the ground is wet.",
  "You can\'t pour that.",
  "Watch it!",
  "Which way?",
  "Oh dear, you seem to have gotten yourself killed.  I might be able to\nhelp you out, but I\'ve never really done this before.  Do you want me\nto try to reincarnate you?",
  "All right.  But don\'t blame me if something goes wr......\n                    --- POOF!! ---\nYou are engulfed in a cloud of orange smoke.  Coughing and gasping,\nyou emerge from the smoke and find....",
  "You clumsy oaf, you\'ve done it again!  I don\'t know how long I can\nkeep this up.  Do you want me to try reincarnating you again?",
  "Okay, now where did I put my orange smoke?....  >POOF!<\nEverything disappears in a dense cloud of orange smoke.",
  "Now you\'ve really done it!  I\'m out of orange smoke!  You don\'t expect\nme to do a decent reincarnation without any orange smoke, do you?",
  "Okay, if you\'re so smart, do it yourself!  I\'m leaving!",
  NULL,
  NULL,
  NULL,
  ">>> messages 81 thru 90 are reserved for \"obituaries\". <<<",
  "Sorry, but I no longer seem to remember how it was you got here.",
  "You can\'t carry anything more.  You\'ll have to drop something first.",
  "You can\'t go through a locked steel grate!",
  "I believe what you want is right here with you.",
  "You don\'t fit through a two-inch slit!",
  "I respectfully suggest you go across the bridge instead of jumping.",
  "There is no way across the fissure.",
  "You\'re not carrying anything.",
  "You are currently holding the following:",
  "It\'s not hungry (it\'s merely pinin\' for the fjords).  Besides, you\nhave no bird seed.",
  "The snake has now devoured your bird.",
  "There\'s nothing here it wants to eat (except perhaps you).",
  "You fool, dwarves eat only coal!  Now you\'ve made him *REALLY* mad!!",
  "You have nothing in which to carry it.",
  "Your bottle is already full.",
  "There is nothing here with which to fill the bottle.",
  "Your bottle is now full of water.",
  "Your bottle is now full of oil.",
  "You can\'t fill that.",
  "Don\'t be ridiculous!",
  "The door is extremely rusty and refuses to open.",
  "The plant indignantly shakes the oil off its leaves and asks, \"Water?\"",
  "The hinges are quite thoroughly rusted now and won\'t budge.",
  "The oil has freed up the hinges so that the door will now move,\nalthough it requires some effort.",
  "The plant has exceptionally deep roots and cannot be pulled free.",
  "The dwarves\' knives vanish as they strike the walls of the cave.",
  "Something you\'re carrying won\'t fit through the tunnel with you.\nYou\'d best take inventory and drop something.",
  "You can\'t fit this five-foot clam through that little passage!",
  "You can\'t fit this five-foot oyster through that little passage!",
  "I advise you to put down the clam before opening it.  >STRAIN!<",
  "I advise you to put down the oyster before opening it.  >WRENCH!<",
  "You don\'t have anything strong enough to open the clam.",
  "You don\'t have anything strong enough to open the oyster.",
  "A glistening pearl falls out of the clam and rolls away.  Goodness,\nthis must really be an oyster.  (I never was very good at identifying\nbivalves.)  Whatever it is, it has now snapped shut again.",
  "The oyster creaks open, revealing nothing but oyster inside.  It\npromptly snaps shut again.",
  "You have crawled around in some little holes and found your way\nblocked by a recent cave-in.  You are now back in the main passage.",
  "There are faint rustling noises from the darkness behind you.",
  "Out from the shadows behind you pounces a bearded pirate!  \"Har, har,\"\nhe chortles, \"I\'ll just take all this booty and hide it away with me\nchest deep in the maze!\"  He snatches your treasure and vanishes into\nthe gloom.",
  "A sepulchral voice reverberating through the cave, says, \"Cave closing\nsoon.  All adventurers exit immediately through main office.\"",
  "A mysterious recorded voice groans into life and announces:\n   \"This exit is closed.  Please leave via main office.\"",
  "It looks as though you\'re dead.  Well, seeing as how it\'s so close to\nclosing time anyway, I think we\'ll just call it a day.",
  "The sepulchral voice intones, \"The cave is now closed.\"  As the echoes\nfade, there is a blinding flash of light (and a small puff of orange\nsmoke). . . .    As your eyes refocus, you look around and find...",
  "There is a loud explosion, and a twenty-foot hole appears in the far\nwall, burying the dwarves in the rubble.  You march through the hole\nand find yourself in the main office, where a cheering band of\nfriendly elves carry the conquering adventurer off into the sunset.",
  "There is a loud explosion, and a twenty-foot hole appears in the far\nwall, burying the snakes in the rubble.  A river of molten lava pours\nin through the hole, destroying everything in its path, including you!",
  "There is a loud explosion, and you are suddenly splashed across the\nwalls of the room.",
  "The resulting ruckus has awakened the dwarves.  There are now several\nthreatening little dwarves in the room with you!  Most of them throw\nknives at you!  All of them get you!",
  "Oh, leave the poor unhappy bird alone.",
  "I daresay whatever you want is around here somewhere.",
  "I don\'t know the word \"stop\".  Use \"quit\" if you want to give up.",
  "You can\'t get there from here.",
  "You are being followed by a very large, tame bear.",
  "For a summary of the most recent changes to the game, say \"news\".\nIf you want to end your adventure early, say \"quit\".  To suspend your\nadventure such that you can continue later, say \"suspend\" (or \"pause\"\nor \"save\").  To see how well you\'re doing, say \"score\".  To get full\ncredit for a treasure, you must have left it safely in the building,\nthough you get partial credit just for locating it.  You lose points\nfor getting killed, or for quitting, though the former costs you more.\nThere are also points based on how much (if any) of the cave you\'ve\nmanaged to explore; in particular, there is a large bonus just for\ngetting in (to distinguish the beginners from the rest of the pack),\nand there are other ways to determine whether you\'ve been through some\nof the more harrowing sections.  If you think you\'ve found all the\ntreasures, just keep exploring for a while.  If nothing interesting\nhappens, you haven\'t found them all yet.  If something interesting\n*DOES* happen (incidentally, there *ARE* ways to hasten things along),\nit means you\'re getting a bonus and have an opportunity to garner many\nmore points in the Master\'s section.  I may occasionally offer hints\nif you seem to be having trouble.  If I do, I\'ll warn you in advance\nhow much it will affect your score to accept the hints.  Finally, to\nsave time, you may specify \"brief\", which tells me never to repeat the\nfull description of a place unless you explicitly ask me to.",
  "Now let\'s see you do it without suspending in mid-Adventure.",
  "There is nothing here with which to fill it.",
  "The sudden change in temperature has delicately shattered the vase.",
  "It is beyond your power to do that.",
  "I don\'t know how.",
  "It is too far up for you to reach.",
  "You killed a little dwarf.  The body vanishes in a cloud of greasy\nblack smoke.",
  "The shell is very strong and is impervious to attack.",
  "What\'s the matter, can\'t you read?  Now you\'d best start over.",
  "The axe bounces harmlessly off the dragon\'s thick scales.",
  "The dragon looks rather nasty.  You\'d best not try to get by.",
  "The little bird attacks the green dragon, and in an astounding flurry\ngets burnt to a cinder.  The ashes blow away.",
  "On what?",
  "Okay, from now on I\'ll only describe a place in full the first time\nyou come to it.  To get the full description, say \"look\".",
  "Trolls are close relatives with the rocks and have skin as tough as\nthat of a rhinoceros.  The troll fends off your blows effortlessly.",
  "The troll deftly catches the axe, examines it carefully, and tosses it\nback, declaring, \"Good workmanship, but it\'s not valuable enough.\"",
  "The troll catches your treasure and scurries away out of sight.",
  "The troll refuses to let you cross.",
  "There is no longer any way across the chasm.",
  "Just as you reach the other side, the bridge buckles beneath the\nweight of the bear, which was still following you around.  You\nscrabble desperately for support, but as the bridge collapses you\nstumble back and fall into the chasm.",
  "The bear lumbers toward the troll, who lets out a startled shriek and\nscurries away.  The bear soon gives up the pursuit and wanders back.",
  "The axe misses and lands near the bear where you can\'t get at it.",
  "With what?  Your bare hands?  Against *HIS* bear hands??",
  "The bear is confused; he only wants to be your friend.",
  "For crying out loud, the poor thing is already dead!",
  "The bear eagerly wolfs down your food, after which he seems to calm\ndown considerably and even becomes rather friendly.",
  "The bear is still chained to the wall.",
  "The chain is still locked.",
  "The chain is now unlocked.",
  "The chain is now locked.",
  "There is nothing here to which the chain can be locked.",
  "There is nothing here to eat.",
  "Do you want the hint?",
  "Do you need help getting out of the maze?",
  "You can make the passages look less alike by dropping things.",
  "Are you trying to explore beyond the plover room?",
  "There is a way to explore that region without having to worry about\nfalling into a pit.  None of the objects available is immediately\nuseful in discovering the secret.",
  "Do you need help getting out of here?",
  "Don\'t go west.",
  "Gluttony is not one of the troll\'s vices.  Avarice, however, is.",
  "Your lamp is getting dim.  You\'d best start wrapping this up, unless\nyou can find some fresh batteries.  I seem to recall there\'s a vending\nmachine in the maze.  Bring some coins with you.",
  "Your lamp has run out of power.",
  "Please answer the question.",
  "There are faint rustling noises from the darkness behind you.  As you\nturn toward them, the beam of your lamp falls across a bearded pirate.\nHe is carrying a large chest.  \"Shiver me timbers!\" he cries, \"I\'ve\nbeen spotted!  I\'d best hie meself off to the maze to hide me chest!\"\nWith that, he vanishes into the gloom.",
  "Your lamp is getting dim.  You\'d best go back for those batteries.",
  "Your lamp is getting dim.  I\'m taking the liberty of replacing the\nbatteries.",
  "Your lamp is getting dim, and you\'re out of spare batteries.  You\'d\nbest start wrapping this up.",
  "You sift your fingers through the dust, but succeed only in\nobliterating the cryptic message.",
  "Do you need help dealing with the ogre?",
  "Hmmm, this looks like a clue, which means it\'ll cost you 10 points to\nread it.  Should I go ahead and read it anyway?",
  "It says, \"There is a way out of this place.  Do you need any more\ninformation to escape?  Sorry, but this initial hint is all you get.\"",
  "There is nothing the presence of which will prevent you from defeating\nhim; thus it can\'t hurt to fetch everything you possibly can.",
  "I\'m afraid I don\'t understand.",
  "Your hand passes through it as though it weren\'t there.",
  "You strike the mirror a resounding blow, whereupon it shatters into a\nmyriad tiny fragments.",
  "You have taken the vase and hurled it delicately to the ground.",
  "You prod the nearest dwarf, who wakes up grumpily, takes one look at\nyou, curses, and grabs for his axe.",
  "Is this acceptable?",
  "This adventure is already over.  To start a new adventure, or to\nresume an earlier adventure, please run a fresh copy of the program.",
  "The ogre doesn\'t appear to be hungry.",
  "The ogre, who despite his bulk is quite agile, easily dodges your\nattack.  He seems almost amused by your puny effort.",
  "The ogre, distracted by your rush, is struck by the knife.  With a\nblood-curdling yell he turns and bounds after the dwarves, who flee\nin panic.  You are left alone in the room.",
  "The ogre, distracted by your rush, is struck by the knife.  With a\nblood-curdling yell he turns and bounds after the dwarf, who flees\nin panic.  You are left alone in the room.",
  "The bird flies about agitatedly for a moment.",
  "The bird flies agitatedly about the cage.",
  "The bird flies about agitatedly for a moment, then disappears through\nthe crack.  It reappears shortly, carrying in its beak a jade\nnecklace, which it drops at your feet.",
  "The urn is now lit.",
  "The urn is now dark.",
  "You empty the bottle into the urn, which promptly ejects the water\nwith uncanny accuracy, squirting you directly between the eyes.",
  "Your bottle is now empty and the urn is full of oil.",
  "The urn is already full of oil.",
  "There\'s no way to get the oil out of the urn.",
  "The urn is far too firmly embedded for your puny strength to budge it.",
  "As you rub the urn, there is a flash of light and a genie appears.\nHis aspect is stern as he advises: \"One who wouldst traffic in\nprecious stones must first learn to recognize the signals thereof.\"\nHe wrests the urn from the stone, leaving a small cavity.  Turning to\nface you again, he fixes you with a steely eye and intones: \"Caution!\"\nGenie and urn vanish in a cloud of amber smoke.  The smoke condenses\nto form a rare amber gemstone, resting in the cavity in the rock.",
  "I suppose you collect doughnut holes, too?",
  "The gem fits easily into the cavity.",
  "The persian rug stiffens and rises a foot or so off the ground.",
  "The persian rug draped over your shoulder seems to wriggle for a\nmoment, but then subsides.",
  "The persian rug settles gently to the ground.",
  "The rug hovers stubbornly where it is.",
  "The rug does not appear inclined to cooperate.",
  "If you mean to use the persian rug, it does not appear inclined to\ncooperate.",
  "Though you flap your arms furiously, it is to no avail.",
  "You board the persian rug, which promptly whisks you across the chasm.\nYou have time for a fleeting glimpse of a two thousand foot drop to a\nmighty river; then you find yourself on the other side.",
  "The rug ferries you back across the chasm.",
  "All is silent.",
  "The stream is gurgling placidly.",
  "The wind whistles coldly past your ears.",
  "The stream splashes loudly into the pool.",
  "You are unable to make anything of the splashing noise.",
  "You can hear the murmuring of the beanstalks and the snoring of the\ndwarves.",
  "A loud hissing emanates from the snake pit.",
  "The air is filled with a dull rumbling sound.",
  "The roar is quite loud here.",
  "The roaring is so loud that it drowns out all other sound.",
  "The bird eyes you suspiciously and flutters away.  A moment later you\nfeel something wet land on your head, but upon looking up you can see\nno sign of the culprit.",
  "There are only a few drops--not enough to carry.",
  "Your head buzzes strangely for a moment.",
  "(Uh, y\'know, that wasn\'t very bright.)",
  "It\'s a pity you took so long about it.",
  "Are you wondering what to do here?",
  "This section is quite advanced.  Find the cave first.",
  "Upstream or downstream?",
  "Wizards are not to be disturbed by such as you.",
  "Would you like to be shown out of the forest?",
  "Go east ten times.  If that doesn\'t get you out, then go south, then\nwest twice, then south.",
  "The waters are crashing loudly against the shore.",
  "%d of them throw knives at you!",
  "%d of them get you!",
  "One of them gets you!",
  "None of them hits you!",
  "Sorry, I don\'t know the word \"%s\".",
  "What do you want to do with the %L?",
  "I see no %L here.",
  "%C what?",
  "Okay, \"%s\".",
  "You have garnered %d out of a possible %d points, using %d turn%S.",
  "I can suspend your Adventure for you so that you can resume later, but\nit will cost you 5 points.",
  "I am prepared to give you a hint, but it will cost you %d point%S.",
  "You scored %d out of a possible %d, using%d turn%S.",
  "To achieve the next higher rating, you need %d more point%S.",
  "To achieve the next higher rating would be a neat trick!\nCongratulations!!",
  "You just went off my scale!!",
  "To resume your Adventure, start a new game and then say \"RESUME\".",
  "Table space used:\n%d of %d words of messages   %d of %d travel options\n%d of %d vocabulary words    %d of %d locations\n%d of %d objects             %d of %d action verbs\n%d of %d \"random\" messages   %d of %d \"class\" messages\n%d of %d hints               %d of %d turn threshholds",
  "To resume an earlier Adventure, you must abandon the current one.",
  "I\'m sorry, but that Adventure was begun using Version%d.%d of the\nprogram, and this is Version%d.%d.  You must find the other version\nin order to resume that Adventure.",
  "A dark fog creeps in to surround you.  From somewhere in the fog you\nhear a stern voice.  \"This Adventure has been tampered with!  You have\nbeen dabbling in magic, knowing not the havoc you might cause thereby.\nLeave at once, before you do irrevocable harm!\"  The fog thickens,\nuntil at last you can see nothing at all.  Your vision then clears,\nand you find yourself back in The Real World.",
  "Guess again.",
  "You\'re missing only one other treasure.  Do you need help finding it?",
  "Once you\'ve found all the other treasures, it is no longer possible to\nlocate the one you\'re now missing.",
  "Sorry, but the path twisted and turned so much that I can\'t figure\nout which way to go to get back.",
  "Open Adventure is an author-approved open-source release of\nVersion 2.5 with, as yet, no gameplay changes.\nVersion 2.5 was essentially the same as Version II; the cave and the\nhazards therein are unchanged, and top score is still 430 points.\nThere are a few more hints, especially for some of the more obscure\npuzzles.  There are a few minor bugfixes and cosmetic changes.  You\ncan now save a game and resume it at once (formerly you had to wait a\nwhile first), but it now costs you a few points each time you save the\ngame.  Saved games are now stored in much smaller files than before.",
  "You don\'t have to say \"go\" every time; just specify a direction or, if\nit\'s nearby, name the place to which you wish to move.",
  NULL,
};

char* class_messages[] = {
  NULL,
  "You are obviously a rank amateur.  Better luck next time.",
  "Your score qualifies you as a novice class adventurer.",
  "You have achieved the rating: \"Experienced Adventurer\".",
  "You may now consider yourself a \"Seasoned Adventurer\".",
  "You have reached \"Junior Master\" status.",
  "Your score puts you in Master Adventurer Class C.",
  "Your score puts you in Master Adventurer Class B.",
  "Your score puts you in Master Adventurer Class A.",
  "All of Adventuredom gives tribute to you, Adventurer Grandmaster!",
  "Adventuredom stands in awe -- you have now joined the ranks of the\n       W O R L D   C H A M P I O N   A D V E N T U R E R S !\nIt may interest you to know that the Dungeon-Master himself has, to\nmy knowledge, never achieved this threshhold in fewer than 330 turns.",
};

char* turn_threshold_messages[] = {
  NULL,
  "Tsk!  A wizard wouldn\'t have to take 350 turns.  This is going to cost\nyou a couple of points.",
  "500 turns?  That\'s another few points you\'ve lost.",
  "Are you still at it?  Five points off for exceeding 1000 turns!",
  "Good grief, don\'t you *EVER* give up?  Do you realize you\'ve spent\nover 2500 turns at this?  That\'s another ten points off, a total of\ntwenty points lost for taking so long.",
};
