= README for Open Adventure =

If you are reading this anywhere but at http://www.catb.org/~esr/open-adventure
you can go there for tarball downloads and other resources.

This code is a forward-port of the Crowther/Woods Adventure 2.5 from
1995, last version in the main line of Colossal Cave Adventure
development written by the original authors.  The authors have given
permission and encouragement for this release; it obsolesces all
the 350-point versions and previous 2.x (430-point) ports.

The file history.adoc contains a more detailed history of this game
and its ancestors.  The file notes.adoc is the maintainer's notes,
describing project goals and recent changes.

This project is called "Open Adventure" because it's not at all clear
how to number Adventure past 2.5 without misleading or causing
collisions or both.  See the history file for discussion.  The
original 6-character name on the PDP-10 has been reverted to for the
executable in order to avoid a collision with the BSD games port of
the ancestral 1977 version.

Please see INSTALL.adoc for build info.

Extreme care has been taken to not silently change gameplay. By
policy, all user-visible changes from 2.5 are revertible with the
-o (oldstyle) command-line option.

If you encounter a bug (not likely; this code is old and well tested)
please try to make a test log that reproduces it, using the -l option,
and ship it to the maintainers.

// end



