= Open Adventure CE =

This is a port of http://www.catb.org/~esr/open-adventure[Open Adventure] to the TI-84 Plus CE.

=== Usage ===

==== Installation ====

The https://github.com/CE-Programming/libraries[standard LoadLib libraries GRAPHX and FILEIOC] are required.

Additionally, FontLibC, a library not currently packaged with LoadLib (though it will be in the next release), is also required.
A compatible copy of FontLibC is included with current releases.
You also need the Times and Dr. Sans fonts, also included.

==== Usage ====

===== Command Shortcuts =====

The following standard command shortcuts are available:

* `i` for `inventory`
* `g` for `get` or `take`
* `l` for `look`
* `u` and `d` for `up` and `down`, respectively
* `n`, `e`, `w`, and `s` for `north`, `east`, `west`, and `south`, respectively
* `ne`, `nw`, `se`, `sw` for northeast, northwest, southeast, and southwest. Note that because the text parser only looks at the first five letters of each word, those are, in fact, the *only* way to enter those directions!

===== Command History =====

While playing, you can press UP to access your command history.
Press ENTER to paste the selected command.
Press CLEAR to return to editing.
DEL is backspace.

===== Saving and Resuming =====

Currently, the Resume command on the main menu doesn't do anything.
This will eventually be fixed.

You can still save and resume games, however.
To resume a saved game, start a new game, answer `no` (or `yes`) to whether you want instructions,
and then type `resume` to resume a game.

==== Battery Saving ====

To prevent ruining your battery, Adventure will automatically quit after several minutes of no key presses.
If you resumed a previously saved game, Adventure will automatically overwrite that save before quitting.
If you're playing a new game, you can manually set the save name using the `filename` command.
However, if you do not set a save name, then the game will be discarded.

You can quit the game instantly at any time by pressing ON, then CLEAR.
*Nothing will be saved.*

=== Technical ===
I looked at several different implementations of Adventure.
They generally required a large text database that would be difficult to get onto a calculator,
and would be needlessly inefficient space-wise.
Then I found Open Adventure, which completely reworked the text database system into native C arrays.
Not only that, but the code was written in fairly idiomatic C, not machine-translated from Fortran!

However, given the constraints and conventions of the platform,
it made sense to split the dungeon data back into a separate data file---but this time, 
there was a convenient `make_dungeon.py` that could be modified to generate the data file,
instead of trying to write my own code to parse the input data.
Helpfully, ESR wrote a comprehensive test suite to compare his new C code against the original.
This made it easy for me to check that my completely reworked dungeon loader didn't break the game.
Unfortunately, keeping tests working requires some akward `#ifdef`s scattered around the code,
but it's worth it to keep the tests working.


= README for Open Adventure PC =

If you are reading this anywhere but at http://www.catb.org/~esr/open-adventure
you can go there for tarball downloads and other resources.

This code is a forward-port of the Crowther/Woods Adventure 2.5 from
1995, last version in the main line of Colossal Cave Adventure
development written by the original authors.  The authors have given
permission and encouragement for this release; it obsolesces all
the 350-point versions and previous 2.x (430-point) ports.

The file history.adoc contains a more detailed history of this game
and its ancestors.  The file notes.adoc is the maintainer's notes,
describing project goals and recent changes.

This project is called "Open Adventure" because it's not at all clear
how to number Adventure past 2.5 without misleading or causing
collisions or both.  See the history file for discussion.  The
original 6-character name on the PDP-10 has been reverted to for the
executable in order to avoid a collision with the BSD games port of
the ancestral 1977 version.

Please see INSTALL.adoc for build info.

Extreme care has been taken to not silently change gameplay. By
policy, all user-visible changes from 2.5 are revertible with the
-o (oldstyle) command-line option.

If you encounter a bug (not likely; this code is old and well tested)
please try to make a test log that reproduces it, using the -l option,
and ship it to the maintainers.

// end



