= Open Adventure CE =

This is a port of http://www.catb.org/~esr/open-adventure[Open Adventure] to the TI-84 Plus CE.

=== Usage ===

==== Installation ====

The https://github.com/CE-Programming/libraries[standard LoadLib libraries GRAPHX and FILEIOC] are required.

Additionally, FontLibC, a library not currently packaged with LoadLib (though it will be in the next release), is also required.
A compatible copy of FontLibC is included with current releases.

You also need the Times and Dr. Sans font packs, also included. Two versions of the Times font pack are included. The Times.8xv font pack contains several font sizes unused by Adventure, so I've also included a Times_mini.8xv file, which only contains the font sizes used by Adventure; it saves about 30 K.

Send both ADVENT.8xp and ADVENT_data.8xv to your calculator. The program `ADVENT` is the game itself, while the appvar `AdvenDat` is the game's dungeon data file. While changes to `AdvenDat` should be rare, different versions of the file are not compatible. If the game complains that the dungeon file is missing, make sure you have the right version of `AdvenDat`.

==== Usage ====

===== Command Shortcuts =====

The following standard command shortcuts are available:

* `i` for `inventory`
* `g` for `get` or `take`
* `l` for `look`; or alternatively, `x` for `examine` (does the same thing)
* `u` and `d` for `up` and `down`, respectively
* `n`, `e`, `w`, and `s` for `north`, `east`, `west`, and `south`, respectively
* `ne`, `nw`, `se`, `sw` for northeast, northwest, southeast, and southwest. Note that because the text parser only looks at the first five letters of each word, those are, in fact, the *only* way to enter those directions!
* `z` to do nothing for a turn (this may still cause other events to proceed)

===== Command History =====

While playing, you can press UP to access your command history.
Press ENTER to paste the selected command.
Press CLEAR to return to editing.
DEL is backspace.

===== Saving and Resuming =====

To save a game currently in progress, type `save`.
You will be prompted for a file name to give the save.
If you previously resumed the game, then it will default to using the same name.
If the save file was archived, it will be rearchived for you.

You can resume a game using the Resume option on the main menu.
Simply use the cursor to select a save file, and then press ENTER to resume that game.
You can delete a file directly from the Resume menu using the DEL key.
Archived files on the Resume menu have a dot to the left of their name.
You can archive a save file at the Resume screen using the STAT key.

(Due to a bug in the FileIOC library (as of June 2019), unarchiving does not currently work.
This will be fixed in the next release of the C libraries.
Adventure already has the unarchive code.
It will become functional as soon as FileIOC is updated.
Saving over an archived file still functions correctly.)


==== Battery Saving ====

To prevent ruining your battery, Adventure will automatically quit after several minutes of no key presses.
If you resumed a previously saved game, Adventure will automatically overwrite that save before quitting.
If you're playing a new game, you can manually set the save name using the `filename` command.
However, if you do not set a save name, then the game will be discarded.

You can quit the game instantly at any time by pressing ON, then CLEAR.
*Nothing will be saved.*




== README for Open Adventure PC ==

ESR's home site for this project is at http://www.catb.org/~esr/open-adventure .
You can go there for tarball downloads and other resources related to his
original PC/POSIX version of this game.

This code is a forward-port of the Crowther/Woods Adventure 2.5 from
1995, last version in the main line of Colossal Cave Adventure
development written by the original authors.  The authors have given
permission and encouragement for this release; it obsolesces all
the 350-point versions and previous 2.x (430-point) ports.

The file history.adoc contains a more detailed history of this game
and its ancestors.  The file notes.adoc is the maintainer's notes,
describing project goals and recent changes.

This project is called "Open Adventure" because it's not at all clear
how to number Adventure past 2.5 without misleading or causing
collisions or both.  See the history file for discussion.  The
original 6-character name on the PDP-10 has been reverted to for the
executable in order to avoid a collision with the BSD games port of
the ancestral 1977 version.

Please see INSTALL.adoc for build info.


// end



