<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>LCOV - advent.info</title>
    <link rel="stylesheet" type="text/css" href="gcov.css">
    <style>
        .covered {{
            text-align: center;
            background-color: #A7FC9D;
        }}
        .covered::before {{
            content: '\002714';
        }}
        .uncovered {{
            text-align: center;
            background-color: #FF0000;
        }}
        .uncovered::before {{
            content: '\002715';
        }}
    </style>
</head>

<body>
    <table width="100%" border=0 cellspacing=0 cellpadding=0>
        <tr><td class="title">adventure.yaml Coverage report</td></tr>
        <tr><td class="ruler"><img src="glass.png" width=3 height=3 alt=""></td></tr>
        <tr>
          <td width="100%">
            <table cellpadding=1 border=0 width="100%">
              <tr>
                <td width="10%"></td>
                <td width="35%"></td>
                <td width="20%"></td>
                <td width="5%"></td>
                <td width="10%" class="headerCovTableHead">Total</td>
                <td width="10%" class="headerCovTableHead">Covered</td>
                <td width="10%" class="headerCovTableHead">% Coverage</td>
              </tr>
              <tr>
                <td class="headerItem">Test:</td>
                <td class="headerValue">adventure.yaml</td>
                <td></td>
                <td class="headerItem">Locations:</td>
                <td class="headerCovTableEntry">{}</td>
                <td class="headerCovTableEntry">{}</td>
                <td class="headerCovTableEntry">{}%</td>
              </tr>
              <tr>
                <td class="headerItem">Date:</td>
                <td class="headerValue">2017-07-07 21:47:56</td>
                <td></td>
                <td class="headerItem">Arbitrary Messages:</td>
                <td class="headerCovTableEntry">{}</td>
                <td class="headerCovTableEntry">{}</td>
                <td class="headerCovTableEntry">{}%</td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td class="headerItem">Objects:</td>
                <td class="headerCovTableEntry">{}</td>
                <td class="headerCovTableEntry">{}</td>
                <td class="headerCovTableEntry">{}%</td>
              </tr>
              <tr><td><img src="glass.png" width=3 height=3 alt=""></td></tr>
            </table>
          </td>
        </tr>
        <tr><td class="ruler"><img src="glass.png" width=3 height=3 alt=""></td></tr>
    </table>
    <br>

    <center>
        <table width="60%" cellpadding=1 cellspacing=1 border=0>
            <tr>
                <td class="tableHead">Location</td>
                <td class="tableHead">long</td>
                <td class="tableHead">short</td>
            </tr>
            {}
        </table>
        <br>

        <table width="60%" cellpadding=1 cellspacing=1 border=0>
            <tr>
                <td class="tableHead">Arbitrary Message</td>
                <td class="tableHead">Covered?</td>
            </tr>
            {}
        </table>
        <br>

        <table width="60%" cellpadding=1 cellspacing=1 border=0>
            <tr>
                <td class="tableHead">Objects</td>
                <td class="tableHead">Covered?</td>
            </tr>
            {}
        </table>
    </center>
    <br>

    <table width="100%" border=0 cellspacing=0 cellpadding=0>
        <tr><td class="ruler"><img src="glass.png" width=3 height=3 alt=""></td></tr>
        <tr><td class="versionInfo">Generated by: <a href="https://gitlab.com/esr/open-adventure/blob/master/tests/coverage_dungeon.py">Open Adventure Dungeon Coverage Generator</a></td></tr>
    </table>
    <br>
</body>
</html>
